version: '3'

vars:
  GRAPHDB_VERS: 10.8.5 # use only 10.x.x versions otherwise you will have license issues, for testing that is totally fine
  VERS: v0.0.3

tasks:
  default:
    desc: Display project information
    cmds:
      - echo "pxgraphdb service - GraphDB Repository and Graph Management API"
      - echo "Version {{.VERS}}"
      - echo ""
      - echo "Available tasks"
      - task --list

  # Testing tasks
  test:
    desc: Run unit tests
    cmds:
      - go test -v ./...

  test:unit:
    desc: Run unit tests with coverage
    cmds:
      - echo "Running unit tests with coverage..."
      - go test -v -coverprofile=coverage.out ./... || test -f coverage.out
      - echo "Coverage report generated at coverage.out"

  test:coverage:
    desc: Generate and view HTML coverage report
    deps: [test:unit]
    cmds:
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage HTML report generated at coverage.html"

  test:verbose:
    desc: Run tests with verbose output
    cmds:
      - go test -v -race ./...

  test:integration:
    desc: Run integration tests (requires GraphDB instances)
    cmds:
      - echo "Running integration tests..."
      - go test -v -tags=integration -timeout=10m ./cmd
      - echo "Integration tests completed"

  test:integration:setup:
    desc: Setup GraphDB instances for integration testing
    cmds:
      - echo "Setting up GraphDB {{.GRAPHDB_VERS}} instances for integration testing..."
      - docker pull ontotext/graphdb:{{.GRAPHDB_VERS}}
      - docker rm -f graphdb-source-test || true
      - docker rm -f graphdb-target-test || true
      - docker run -d --name graphdb-source-test -p 7201:7200 -e GDB_HEAP_SIZE=2g ontotext/graphdb:{{.GRAPHDB_VERS}}
      - docker run -d --name graphdb-target-test -p 7202:7200 -e GDB_HEAP_SIZE=2g ontotext/graphdb:{{.GRAPHDB_VERS}}
      - echo "Waiting for GraphDB instances to start (60 seconds)..."
      - sleep 60
      - echo "GraphDB {{.GRAPHDB_VERS}} instances ready:"
      - echo "  - Source at http://localhost:7201"
      - echo "  - Target at http://localhost:7202"

  test:integration:teardown:
    desc: Stop and remove integration test GraphDB instances
    cmds:
      - echo "Stopping integration test GraphDB instances..."
      - docker rm -f graphdb-source-test || true
      - docker rm -f graphdb-target-test || true
      - echo "Integration test instances stopped and removed"

  test:integration:full:
    desc: Run full integration test suite (setup, test, teardown)
    cmds:
      - task: test:integration:setup
      - task: test:integration
      - task: test:integration:teardown

  # Code quality tasks
  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  templ:generate:
    desc: Generate Go code from Templ templates
    cmds:
      - templ generate
      - echo "Templ templates generated successfully"

  vet:
    desc: Run Go vet
    cmds:
      - go vet ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  # Build tasks
  build:
    desc: Build the application
    cmds:
      - go build -o graphservice main.go
      - echo "Binary built at graphservice"

  build:versioned:
    desc: Build with version information
    cmds:
      - |
        go build \
          -ldflags="-X 'github.com/spf13/cobra.version={{.VERS}}' \
                    -X 'github.com/spf13/cobra.commit=$(git rev-parse HEAD)' \
                    -X 'github.com/spf13/cobra.date=$(date -u +%Y-%m-%dT%H:%M:%SZ)'" \
          -o graphservice main.go
      - echo "Versioned binary built at graphservice"

  # Docker and container tasks
  local-setup:
    desc: Start local GraphDB instances for testing
    cmds:
      - docker pull ontotext/graphdb:{{.GRAPHDB_VERS}}
      - docker rm -f test-src-graphdb || true
      - docker rm -f test-tgt-graphdb || true
      - docker run -d --name test-src-graphdb -p 7201:7200 ontotext/graphdb:{{.GRAPHDB_VERS}}
      - docker run -d --name test-tgt-graphdb -p 7202:7200 ontotext/graphdb:{{.GRAPHDB_VERS}}
      - cmd: echo "GraphDB instances started"
      - cmd: echo "  - Source at http://localhost:7201"
      - cmd: echo "  - Target at http://localhost:7202"

  local-teardown:
    desc: Stop and remove local GraphDB instances
    cmds:
      - docker rm -f test-src-graphdb || true
      - docker rm -f test-tgt-graphdb || true
      - echo "GraphDB instances stopped and removed"

  image-build-local:
    desc: Build and push Docker image
    cmds:
      - nixpacks build . --name private.hz.pantopix.net/pxgraphdb/service:{{.VERS}}
      - docker tag private.hz.pantopix.net/pxgraphdb/service:{{.VERS}} private.hz.pantopix.net/pxgraphdb/service:latest
      - docker push private.hz.pantopix.net/pxgraphdb/service:{{.VERS}}
      - docker push private.hz.pantopix.net/pxgraphdb/service:latest
      - echo "Docker image built and pushed {{.VERS}}"

  # Cleanup tasks
  clean:
    desc: Clean build artifacts and test files
    cmds:
      - rm -f graphservice
      - rm -f coverage.out coverage.html
      - rm -f *.ttl *.brf *.rdf
      - echo "Cleaned build artifacts and test files"

  # CI tasks
  ci:
    desc: Run all CI checks (test, vet, fmt check)
    cmds:
      - task: test:unit
      - task: vet
      - gofmt -l . | grep -v '^$' && echo "Files need formatting" && exit 1 || echo "All files formatted correctly"
      - echo "All CI checks passed!"

  # Development tasks
  dev:
    desc: Run the service in development mode
    cmds:
      - echo "Starting GraphDB service in development mode..."
      - echo "Set API_KEY environment variable before running"
      - go run main.go graphdb

  help:
    desc: Show detailed help information
    cmds:
      - echo "GraphDB Service - Task Automation"
      - echo "=================================="
      - echo ""
      - task --list
      - echo ""
      - cmd: echo "Examples:"
      - cmd: echo "  task test              # Run unit tests"
      - cmd: echo "  task test:unit         # Run tests with coverage"
      - cmd: echo "  task build             # Build the binary"
      - cmd: echo "  task local-setup       # Start test GraphDB instances"
      - cmd: echo "  task ci                # Run all CI checks"
