version: '3'

vars:
  GRAPHDB_VERS: 10.8.5 # use only 10.x.x versions otherwise you will have license issues, for testing that is totally fine

tasks:
  default:
    cmds:
      - echo "pxgraphdb service"
  local-setup:
    cmds:
      - docker pull ontotext/graphdb:{{.GRAPHDB_VERS}}
      - docker rm -f test-src-graphdb || true
      - docker rm -f test-tgt-graphdb || true
      - docker run -d --name test-src-graphdb -p 7201:7200 ontotext/graphdb:{{.GRAPHDB_VERS}}
      - docker run -d --name test-tgt-graphdb -p 7202:7200 ontotext/graphdb:{{.GRAPHDB_VERS}}
